# Apio project configuration file.
# See https://fpgawars.github.io/apio/docs/project-file for details.

# This apio.ini demonstrates how the design can be parametrized
# using apio.ini env. The optional command line flag '--env' allows
# to select the env to use.
#
# Example:
#    apio upload --env fast
#
# Note: no env here is named 'default' on purpose -- this example also
# guards against regressions of the xilinx build path issue (apio#918).

# Select the default env. Without it, the first listed
# env is the default.
[apio]
default-env = slow

# Common for all envs.
[common]
board = arty-a7-35t
top-module = main

# Env for build with fast blink.
[env:fast]
defines =
    CLK_DIV=25_000_000

# Env for build with slow blink.
[env:slow]
defines =
    CLK_DIV=100_000_000
