`default_nettype none

// Generated by xc7pll: PLLE2_BASE, input 100 MHz
// input:            100 MHz
// DIVCLK_DIVIDE:    1   (PFD 100 MHz)
// CLKFBOUT_MULT:    16  (VCO 1600 MHz)
// CLKOUT0_DIVIDE:   8  ->  200 MHz (requested 200 MHz, exact)
//
// Generated with:
//   apio raw -- xc7pll -i 100 -o 200 -m -f pll.v
//   apio format pll.v
//
// The `ifdef SYNTHESIS block and the fake implementation were added
// manually so that the same module works in testbenches (the
// PLLE2_BASE primitive is not simulatable without vendor models).

module pll (
    input  wire clk_in,    // 100 MHz
    output wire clk_out0,  // 200 MHz
    output wire locked
);

`ifdef SYNTHESIS

  // Real implementation using the PLLE2_BASE primitive for synthesis.

  wire clk_fb, clk_out0_unbuf;

  PLLE2_BASE #(
      .CLKIN1_PERIOD(10.000),
      .DIVCLK_DIVIDE(1),
      .CLKFBOUT_MULT(16),
      .CLKOUT0_DIVIDE(8)
  ) pll (
      .CLKIN1(clk_in),
      .CLKFBOUT(clk_fb),
      .CLKFBIN(clk_fb),
      .CLKOUT0(clk_out0_unbuf),
      .CLKOUT1(),
      .CLKOUT2(),
      .CLKOUT3(),
      .CLKOUT4(),
      .CLKOUT5(),
      .LOCKED(locked),
      .RST(1'b0),
      .PWRDWN(1'b0)
  );

  BUFG bufg_out0 (
      .I(clk_out0_unbuf),
      .O(clk_out0)
  );

`else

  // Fake implementation for simulation.

  assign clk_out0 = clk_in;
  assign locked  = 1'b1;

`endif

endmodule
